# -*- coding: utf-8 -*-
"""Ptyxiaki.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12oRI4GwiwUErWqkKOSuRTpEBcPJlifEn

## Road Damage Detection
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 1.x
from matplotlib import pyplot as plt
import time

# opencv stuff
import cv2
from preprocessing import lane_detection
import detection


# Loading video images in BGR
video = cv2.VideoCapture('Video Nº 11- Ugly Asphalt cracks (S.A. La Beltraneja).mp4')

out = cv2.VideoWriter('output.avi', cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'), 30, (1280, 720))
# Check if camera opened successfully
if (not video.isOpened()):
    print("Error opening video stream or file")
start_time = time.time()
while (video.isOpened()):
    success, originImg = video.read()
    if success:
        detected = detection.detect(originImg)
        # lined = lane_detection(originImg)
        # image_np,*_ = detect(masked)
        # Display the resulting frame
        plt.imshow(detected)
        # plt.imshow(lined)
        plt.show()
        # out.write(lined)
    else:
        break

video.release()
print("--- %s seconds ---" % (time.time() - start_time))
